### ISSUE TITLE
Improve FieldMask documentation

### ISSUE THREAD

**Issue by edorivai** [googleapis/nodejs-iot#178]
This is just a suggestion to improve the docs.

I was trying to use the [`DeviceManagerClient#listDevices`](https://googleapis.dev/nodejs/iot/latest/v1.DeviceManagerClient.html#listDevices) method to get a list of my devices, but I wanted the response to include the `lastHeartbeatTime` field.

According to the docs, I need to add a `fieldMask` to the `listDevices` request. First off, it's pretty hard to figure out what the expected format of `fieldMask` is. There are no examples whatsoever in the docs, all it says is it should be an Object of the same shape as `FieldMask`.

It then links to a [generic explanation on fieldmasks](https://googleapis.dev/nodejs/iot/latest/google.protobuf.html#.FieldMask), which is even more confusing because the examples there are written in in the protobuf definition language.

I finally manage to figure out that one of the expected formats is something like this

```
{ paths: ["name", "id"] }
```

So I proceed to add `lastHeartbeatTime`:

```
{ paths: ["name", "lastHeartbeatTime"] }
```

Which gives me the following error:

> Error: The field 'lastHeartbeatTime' is invalid

That surprised me, because the actual response objects really _do_ contain a `lastHeartbeatTime` field (which is nulled out by default).

I finally find my way to the protobuf definitions, only to find that in protobuf the fields are defined in snake_case. So the following works:

```
{ paths: ["name", "last_heartbeat_time"] }
```

It seems that the node API is automatically changing the casing to camelCase.

All in all there are quite a few mental steps involved to get fieldMasks to work, which are completely unclear from the docs.

**Comment by bcoe** [comment]
:wave: thanks for the feedback :+1: sounds like something we should definitely consider documenting better.

**Comment by jmeberst** [comment]
Thanks for posting the solution, this one got me good today.

**Comment by peteyhayman** [comment]
for those looking for an example using all device field masks:
`
async function listDevices() {
    const parent = `projects/${projectId}/locations/${cloudRegion}/registries/${registryId}`
    const fieldMask = {
        paths: [
            'credentials',
            'metadata',
            'id',
            'name',
            'num_id',
            'last_heartbeat_time',
            'last_event_time',
            'last_error_time',
            'last_error_status',
            'config',
            'last_config_ack_time',
            'state',
            'last_config_send_time',
            'blocked',
            'last_state_time',
            'log_level',
            'gateway_config'
        ]
    }
    return await client.listDevices({ parent, fieldMask })
}
`

**Comment by peteyhayman** [comment]
out of interest heres a full list of device field masks: 
`
    const fieldMask = {
        paths: [
            'credentials',
            'metadata',
            'id',
            'name',
            'num_id',
            'last_heartbeat_time',
            'last_event_time',
            'last_error_time',
            'last_error_status',
            'config',
            'last_config_ack_time',
            'state',
            'last_config_send_time',
            'blocked',
            'last_state_time',
            'log_level',
            'gateway_config'
        ]
    }
`

**Comment by ari2** [comment]
This really saved my project :)

**Comment by kolban-google** [comment]
Looks like we just got bit again by this issue ...

https://stackoverflow.com/questions/64715487/google-cloud-iot-core-node-js-client-how-to-get-lastheartbeattime-of-a-device-i

**Comment by PopradiArpad** [comment]
The fieldMask documentation could be improved in the
https://cloud.google.com/iot/docs/samples/device-manager-samples#list_devices_in_a_registry
example simple using it:

const [response] = await iotClient.listDevices({
  parent: parentName
  // The properties of the devices you are interested in.
  // For fieldMask values see LINK
  fieldMask: {paths: ['last_heartbeat_time', 'OTHER_EXAMPLE']}
  // For other request properties see https://googleapis.dev/nodejs/iot/latest/v1.DeviceManagerClient.html#listDevices
  });


It would be good when the links in the comments would be real clickable links.

Generally the very useful *Samples* subsection (on the left sidebar) of [**Resources**](https://cloud.google.com/iot/docs/resources) is sadly hidden.
It would be more natural to have it under the menu [**Guides**](https://cloud.google.com/iot/docs/quickstart) (as a subsection on the left sidebar like *Cloud IoT Core*, *How-to guides*, *Concepts* ) because at least in my simple world there is only **Guide** and **Reference** as code documentation.

**Comment by gcseh** [comment]
Thank you all for identifying and raising this issue!

The code examples are updated with fieldMask on the docs page, and also the fieldMask description will be updated on the SDK reference page:
- https://cloud.google.com/iot/docs/samples/device-manager-samples#iot-core-list-devices-nodejs
- https://cloud.google.com/iot/docs/how-tos/devices#iot-core-list-devices-nodejs
- https://googleapis.dev/nodejs/iot/latest/v1.DeviceManagerClient.html#listDevices
