### ISSUE TITLE
Could not load the default credentials

### ISSUE THREAD

**Issue by theolof** [googleapis/nodejs-iot#234]
#### Environment details

  - OS:
Firebase Cloud Functions
  - Node.js version:
v13.2.0
  - npm version:
6.13.1
  - `@google-cloud/iot` version:
1.5.0
#### Steps to reproduce

  1. Initialize a client like this, in Firebase Cloud Functions:
`const deviceManagerClient = new iot.v1.DeviceManagerClient();`
  2. Call this:
`deviceManagerClient.sendCommandToDevice(request)`

The command fails intermittently with
```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/srv/node_modules/google-auth-library/build/src/auth/googleauth.js:161:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

If I use version 0.2.1 of `@google-cloud/iot`, it seems to work fine.
Version 1.5.0 works sometimes, but not always.

**Comment by Transferr3** [comment]
Same error.. 
` Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
>      at GoogleAuth.getApplicationDefaultAsync (/Users/mertozal/node_modules/google-auth-library/build/src/auth/googleauth.js:161:19)
>      at <anonymous>
>      at process._tickCallback (internal/process/next_tick.js:189:7)`

Version 1.6.0 
tried in firebase functions

**Comment by bcoe** [comment]
@Transferr3 a workaround is to create a service account, rather than relying on the default credentials, see:

https://cloud.google.com/docs/authentication/getting-started

I will bring this issue to the attention of some folks on the firestore team :+1:

**Comment by gcseh** [comment]
I hope that 
https://cloud.google.com/docs/authentication/getting-started
helped solving this issue.

Please re-open this ticket if needed.
