### ISSUE TITLE
Protos types are not exported

### ISSUE THREAD

**Issue by JrSchild** [googleapis/nodejs-iot#246]
Types defined in protos are not exported and require a nested path to import them.

#### Environment details

  - OS: Mac OS 10.14
  - Node.js version: 12.6
  - npm version: 6.9.0
  - `@google-cloud/iot` version: 1.6.0

#### Steps to reproduce
As shown below, an import path must currently be specified to access the `PublicKeyFormat` enum. This is undesirable because it requires specifying an internal path,
```typescript
import { v1 } from '@google-cloud/iot';
import { google } from '@google-cloud/iot/build/protos/protos';

const iotClient = new v1.DeviceManagerClient();

const createDevice = async () => {
  await iotClient.createDevice({
    device: {
      credentials: [
        {
          publicKey: {
            format: google.cloud.iot.v1.PublicKeyFormat.ES256_PEM,
            key: 'public-key',
          },
        },
      ],
      id: 'service-id',
    },
    parent: 'device/path',
  });
}
```

**Comment by bcoe** [comment]
@xiaozhenliu-gg5 sounds like we should be exporting these?

**Comment by alexander-fenster** [comment]
We will be exporting this soon. I can assure you though that the current location and filenames (`protos/protos.js`, `protos/protos.d.ts`) will not change without a semver major release, and we don't expect it to change any time soon.

**Comment by JrSchild** [comment]
Thanks @alexander-fenster! For now we will keep the workaround in place.

**Comment by JrSchild** [comment]
Hi @alexander-fenster, any update on exporting the `PublicKeyFormat` type? Or maybe the entire `google` namespace?

**Comment by alexander-fenster** [comment]
@JrSchild It's exported, isn't it?

```
$ npm ls @google-cloud/iot
/private/tmp/iot
└── @google-cloud/iot@2.1.1 

$ grep protos node_modules/\@google-cloud/iot/build/src/index.d.ts 
import * as protos from '../protos/protos';
export { protos };
```

**Comment by JrSchild** [comment]
It appears you are right @alexander-fenster. Thanks!
