### ISSUE TITLE
stop skipping tests

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-iot#322]
#266 has one test that's being skipped, we should come back and see if we can get this to work.

**Comment by gguuss** [comment]
/FYI This issue is now out of SLO. I am ok with disabling the tests that I disabled because the Commands tests are not guaranteed to work and the tests requiring async operations seem to run non-deterministically in the CI without the nodejs devrel tooling.

**Comment by bcoe** [comment]
@gguuss it's fine to simply label this issue as `process`, since it's an improvement we would like to make.

**Comment by gguuss** [comment]
SGTM, thanks @bcoe

**Comment by gcseh** [comment]
closing this for now due lack of resource capacity.
