### ISSUE TITLE
Use the server certificate in the NodeJS example

### ISSUE THREAD

**Issue by sat0yu** [googleapis/nodejs-iot#422]
**Is your feature request related to a problem? Please describe.**
[The document](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge) of using MQTT protocol in Cloud IoT Core mentions [the server certificate](https://cloud.google.com/iot/docs/how-tos/mqtt-bridge#downloading_mqtt_server_certificates).
The NodeJS example, however, [seems to be ignoring that part in the code](https://github.com/googleapis/nodejs-iot/blob/a752a8f/samples/mqtt_example/cloudiot_mqtt_example_nodejs.js#L202-L210).

 **Describe the solution you'd like**
Since all other examples, C++, JAVA, and Python support TLS connection with the server certificate, the one for NodeJS might be better off doing so as well.
- ref. C++ https://github.com/GoogleCloudPlatform/cpp-samples/blob/master/iot/mqtt-ciotc/mqtt_ciotc.c#L68

 **Describe alternatives you've considered**
none

 **Additional context**
none

**Comment by gcseh** [comment]
Thank you for raising this request to us. It has been implemented with #438 .
Therefore I also would like to ask you to close #423 .
