### ISSUE TITLE
Unable to Connect a virtual device to Cloud IoT Core using the MQTT bridge using the command given in tutorial, "Missing required argument: serverCertFile". 

### ISSUE THREAD

**Issue by Matri-Net** [googleapis/nodejs-iot#440]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
mqtt sample issue

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-iot/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
tried all the above  options
3) Do you have a support contract?
No
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Using cloud shell editor on chrome
  - Node.js version: 12.14.1
  - npm version:7.5.3
  - `@google-cloud/iot` version: latest

#### Steps to reproduce

  1. rum below command in google shell editor
  node cloudiot_mqtt_example_nodejs.js mqttDeviceDemo --cloudRegion=us-central1 --proj ectId=nth-setup-305706 --registryId=my-registry --deviceId=my-node-device --privateKeyFile=../rsa_private.pem --numMessages=25 --algorithm=RS256 --mq ttBridgePort=443
  2. output of the command is missing 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by gcseh** [comment]
Please [download root credentials](https://cloud.google.com/iot/docs/quickstart#download_root_credentials) as described in the [quickstart guide](https://cloud.google.com/iot/docs/quickstart) and pass the file path via `serverCertFile` argument.

**Comment by Matri-Net** [comment]
Thank You!! I used wget https://pki.google.com/roots.pem to download certificate.  I was able to complete all the steps in interactive tutorials. This step is missing in interactive tutorials, tutorials should be fixed
Thank You

**Comment by gcseh** [comment]
Yes, I already initiated fixing the tutorials after receiving your bug report.
Thank you again for helping us!
