### ISSUE TITLE
Update sample code to suggest checking for missing default Cloud Pub/Sub topic

### ISSUE THREAD

**Issue by Bogdan-Stancescu-RBC** [googleapis/nodejs-iot#498]
I spent several hours trying to understand why `samples/http_example/cloudiot_http_example.js` was producing errors when attempting to upload telemetry events. The error message was "INVALID_ARGUMENT", when in fact the issue turned out to be that I hadn't created a default Cloud Pub/Sub topic in the registry. I made some changes to the sample code in order to suggest that type of problem to future developers.

The issue should actually be fixed upstream, in Google's ingestor – it should issue a more explicit error (which it does, if you set up a Pub/Sub topic but fail to set it as default; if you set up no Pub/Sub topic at all, you get the INVALID_ARGUMENT error instead). But I won't spend $29 just to tell Google how to improve their product, so I ended up implementing this change in the sample.

I can create a pull request at any time, but apparently I need to file a bug first. Please let me know if this would be useful, or if you find a cleaner way to implement this improvement. My changes are here: https://github.com/Bogdan-Stancescu-RBC/nodejs-iot

**Comment by SurferJeffAtGoogle** [comment]
@gcseh Has the bug been fixed?  Please close this issue.

**Comment by gcseh** [comment]
> @gcseh Has the bug been fixed? Please close this issue.

@SurferJeffAtGoogle No, it was not fixed yet.

**Comment by simoncsaba-g** [comment]
Hi Bogdan,

Thank you again for reporting this issue. 
The bug is fixed now, we should return the correct error message.

Csaba
