### ISSUE TITLE
Migrate samples from nodejs-docs-samples

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-iot#99]
There are currently apiary based samples for iot available here:
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/iot

We should move these over to this repository, and migrate from apiary to gapic based syntax.

**Comment by JustinBeckwith** [comment]
👋 @gguuss

**Comment by gguuss** [comment]
I'm working on it!

**Comment by gguuss** [comment]
Will resolve when #266 lands
